package framesHabitacions;

import classesPrincipals.EstructuraDades;
import framesHabitacions.JFrameGestioHabitacions;
import classesPrincipals.Habitacio;
import javax.swing.table.DefaultTableModel;

/**
 * JFrame de Llista d'Habitacions
 * @author Evaldas Casas
 * @version v0.1
 */

public class JFrameLlistarHabitacio extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLlistarHabitacio
     */
    private DefaultTableModel taula;
    private int row = 0;
    
    
    public JFrameLlistarHabitacio() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void carregarInterficie() {
        String dades[][]={};
        String columnes[] = {"id", "num_hab", "tipus_hab", "num_llits", "tipus_llits", "estat"};
        taula = new DefaultTableModel(dades, columnes) {
            boolean[] canEdit = new boolean[] {
                false, false, false, false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        jTable1.setModel(taula);
        
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        jScrollPane2.setViewportView(jTable1);

        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }
    }
    
    public void mostrarDades(Habitacio hab) {
        taula.insertRow(row, new Object[]{});
        taula.setValueAt(hab.getIdHabitacio(), row, 0);
        taula.setValueAt(hab.getNumHabitacio(), row, 1);
        taula.setValueAt(hab.getTipusHabitacio(), row, 2);
        taula.setValueAt(hab.getNumLlits(), row, 3);
        taula.setValueAt(hab.getTipusLlits(), row, 4);
        taula.setValueAt(hab.getEstatHabitacio(), row, 5);
        row++;
    }
        
        /*
        DefaultTableModel taula = (DefaultTableModel) jTable1.getModel();
        for(int i=0; i< Habitacio.getHabitacionsCreades(); i++) {
            taula.addRow(new Object[]{
                Habitacio.arrayHabitacio[i].getIdHabitacio(),
                Habitacio.arrayHabitacio[i].getNumHabitacio(), 
                Habitacio.arrayHabitacio[i].getTipusHabitacio(), 
                Habitacio.arrayHabitacio[i].getNumLlits(), 
                Habitacio.arrayHabitacio[i].getTipusLlits(),
                Habitacio.arrayHabitacio[i].getEstatHabitacio()
            });
        }
        
        /*jTable1.setValueAt(hab.getIdHabitacio(), row, 0);
        jTable1.setValueAt(hab.getNumHabitacio(), row, 1);
        jTable1.setValueAt(hab.getTipusHabitacio(), row, 2);
        jTable1.setValueAt(hab.getNumLlits(), row, 3);
        jTable1.setValueAt(hab.getTipusLlits(), row, 4);
        jTable1.setValueAt(hab.getEstatHabitacio(), row, 5);
        row++;
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Llistar habitacions");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Llista d'habitacions");

        btnCancelar.setText("Cancel·lar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(0, 313, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        JFrameGestioHabitacions gestioHabitacions = new JFrameGestioHabitacions();
        gestioHabitacions.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameLlistarHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameLlistarHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameLlistarHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameLlistarHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameLlistarHabitacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
