package jframegestioReservaHabitacions;

import classesPrincipals.EstructuraDades;
import classesPrincipals.ReservaHabitacio;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import jframesClient.JFrameMenuClient;

/**
 *
 * @author manel
 */
public class JFrameModificarReservaHabitacio extends javax.swing.JFrame {
    
    private TableRowSorter trsFiltro;

    /**
     * Creates new form JFrameModificarReservaHabitacio
     */
    public JFrameModificarReservaHabitacio() {
        initComponents();
        setLocationRelativeTo(null);
        plenarTaula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar reserva habitació");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Modificar reserva habitació");

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Num Habitacio", "Estat" }));

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFiltroKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Tornar enrere");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        int input = JOptionPane.showConfirmDialog(null, "Estas segur que vols modificar la Reserva?");
        // 0=yes, 1=no, 2=cancel
        if (input == 0) {
            String DNI = jTable1.getValueAt(index, 2).toString();
            String numHabitacio = jTable1.getValueAt(index, 3).toString();
            String dataIn = jTable1.getValueAt(index, 5).toString();
            String dataOut = jTable1.getValueAt(index, 6).toString();
            String estatRes = jTable1.getValueAt(index, 7).toString();
            
            Moduls.ModificarReservaHabitacio.modificarReservaHab(DNI, numHabitacio, dataIn, dataOut, estatRes);
            
            JFrameModificarReservaHabitacioDADES modificarDades = new JFrameModificarReservaHabitacioDADES();
            modificarDades.setVisible(true);
            dispose();
            
        } else if (input == 1) {
            JOptionPane.showMessageDialog(this, "Reserva no modificada");

        } else {
            JFrameMenuReservaHabitacio menu = new JFrameMenuReservaHabitacio();
            menu.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyTyped
        txtFiltro.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (txtFiltro.getText());
                txtFiltro.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(jTable1.getModel());
        jTable1.setRowSorter(trsFiltro);
    }//GEN-LAST:event_txtFiltroKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrameMenuReservaHabitacio menu = new JFrameMenuReservaHabitacio();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarReservaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarReservaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarReservaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameModificarReservaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameModificarReservaHabitacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
    
    private void plenarTaula() {
        DefaultTableModel taula = new DefaultTableModel();
        taula.addColumn("Nom");  //Dono nom a les columnes
        taula.addColumn("Cognom"); //Dono nom a les columnes
        taula.addColumn("DNI"); //Dono nom a les columnes
        taula.addColumn("Num_Hab"); //Dono nom a les columnes
        taula.addColumn("Tip_Hab"); //Dono nom a les columnes
        taula.addColumn("Data_Entrada");
        taula.addColumn("Data_Sortida");
        taula.addColumn("Estat");

        taula.setRowCount(EstructuraDades.arrayReservaHab.size());

        int i = 0;
        for (ReservaHabitacio obj : EstructuraDades.arrayReservaHab) {
            taula.setValueAt(obj.getNomClient(), i, 0);
            taula.setValueAt(obj.getCognomClient(), i, 1);
            taula.setValueAt(obj.getDniClient(), i, 2);
            taula.setValueAt(obj.getNumHabitacio(), i, 3);
            taula.setValueAt(obj.getTipusHabitacio(), i, 4);
            taula.setValueAt(obj.getDataEntrada(), i, 5);
            taula.setValueAt(obj.getDataSortida(), i, 6);
            taula.setValueAt(obj.getEstatReserva(), i, 7);

            i++;
        }
        jTable1.setModel(taula);
    }

    public void filtro() {
        int columnaABuscar = 0;
        if (comboFiltro.getSelectedItem() == "Nom") {
            columnaABuscar = 0;
        }
        if (comboFiltro.getSelectedItem() == "Cognom") {
            columnaABuscar = 1;
        }
        if (comboFiltro.getSelectedItem() == "DNI") {
            columnaABuscar = 2;
        }
        if (comboFiltro.getSelectedItem() == "Numero_Habitacio") {
            columnaABuscar = 3;
        }
        if (comboFiltro.getSelectedItem() == "Tipus_Habitacio") {
            columnaABuscar = 4;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtFiltro.getText(), columnaABuscar));
    }
    
}
