package framesHabitacions;

import GestioHotelLog.GestioHotelLog;
import static GestioHotelLog.GestioHotelLog.LOGGER;
import Moduls.ModulHabitacio;
import classesPrincipals.EstructuraDades;
import classesPrincipals.Habitacio;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.SimpleFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * JFrame de Baixa d'Habitacions
 * @author Evaldas Casas
 * @version v0.1
 */

public class JFrameBaixaHabitacio extends javax.swing.JFrame {

    /**
     * Creates new form BaixaHabitacio
     */
    public JFrameBaixaHabitacio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Funció carregarInterficie
     * Carrega el ComboBox1 amb els Numeros de les Habitacions que hi ha creades
     * Si no hi ha registres en l'array, mostra un avís i retorna a la finestra principal
     */
    public void carregarInterficie() {
        try {
            String[] numHabitacions = new String[EstructuraDades.arrayHabitacio.size()];

            for (int i = 0; i < EstructuraDades.arrayHabitacio.size(); i++) {
                numHabitacions[i] = EstructuraDades.arrayHabitacio.get(i).getNumHabitacio();
            }

            DefaultComboBoxModel box = new DefaultComboBoxModel(numHabitacions);
            jComboBox1.setModel(box);
            jRadioButtonConfirmar.setSelected(false);

            if (jComboBox1.getSelectedItem() == null) {
                int resultat = JOptionPane.showOptionDialog(null, "No hi ha registres creats!", "Error", JOptionPane.DEFAULT_OPTION,
                        JOptionPane.ERROR_MESSAGE, null, null, null);
                if (resultat == 0) {
                    this.setVisible(false);
                    JFrameGestioHabitacions gestioHabitacions = new JFrameGestioHabitacions();
                    gestioHabitacions.setVisible(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            LOGGER.log(Level.INFO, "Exception:",e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcceptarEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButtonConfirmar = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Donar de baixa habitació");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        btnAcceptarEliminar.setText("Acceptar");
        btnAcceptarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancel·lar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Donar de baixa habitació");

        jLabel2.setText("Selecciona el número d'habitació a donar de baixa");

        jRadioButtonConfirmar.setText("Si");

        jLabel3.setText("Estàs segur de voler donar de baixa?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAcceptarEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonConfirmar)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 165, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptarEliminar)
                    .addComponent(btnCancelar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*  */
    private void btnAcceptarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarEliminarActionPerformed
        // TODO add your handling code here
        try {
            if (jComboBox1.getSelectedItem() == null) {
            } else {
                String numHabitacio = String.valueOf(jComboBox1.getSelectedItem());
                boolean shaTrobat = false;

                if (!(jRadioButtonConfirmar.isSelected())) {
                    JOptionPane.showMessageDialog(null, "Has de confirmar si vols donar de baixa!");
                }

                for (int i = 0; i < EstructuraDades.arrayHabitacio.size() && shaTrobat == false; i++) {
                    if (numHabitacio.equals(EstructuraDades.arrayHabitacio.get(i).getNumHabitacio()) && jRadioButtonConfirmar.isSelected()) {
                        shaTrobat = true;
                        GestioHotelLog.LOGGER.log(Level.INFO, "ELIMINAR: {0}", EstructuraDades.arrayHabitacio.get(i).toString());
                        EstructuraDades.arrayHabitacio.remove(i);
                        JOptionPane.showMessageDialog(null, "S'ha esborrat el registre correctament!");
                        carregarInterficie();
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            LOGGER.log(Level.INFO, "Exception:",e);
        }
        
    }//GEN-LAST:event_btnAcceptarEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        JFrameGestioHabitacions gestioHabitacions = new JFrameGestioHabitacions();
        gestioHabitacions.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameBaixaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameBaixaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameBaixaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameBaixaHabitacio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameBaixaHabitacio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptarEliminar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonConfirmar;
    // End of variables declaration//GEN-END:variables
}
